# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Julia/Desktop/hdmi_vga_zybo2/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0.xci
# IP: The module: 'hdmi_vga_vp_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Julia/Desktop/hdmi_vga_zybo2/hdmi_vga_zybo.srcs/sources_1/ip/median5x5_0_3/median5x5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==median5x5_0 || ORIG_REF_NAME==median5x5_0} -quiet] -quiet

# IP: C:/Users/Julia/Desktop/hdmi_vga_zybo2/hdmi_vga_zybo.srcs/sources_1/ip/thresh_0_2/thresh_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==thresh_0 || ORIG_REF_NAME==thresh_0} -quiet] -quiet

# IP: C:/Users/Julia/Desktop/hdmi_vga_zybo2/hdmi_vga_zybo.srcs/sources_1/ip/rgb2ycbcr_0/rgb2ycbcr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb2ycbcr_0 || ORIG_REF_NAME==rgb2ycbcr_0} -quiet] -quiet

# IP: c:/Users/Julia/Desktop/hdmi_vga_zybo2/hdmi_vga_zybo.srcs/sources_1/ip/delayLineBRAM/delayLineBRAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM} -quiet] -quiet

# IP: C:/Users/Julia/Desktop/hdmi_vga_zybo2/hdmi_vga_zybo.srcs/sources_1/ip/divider_32_20_0_1/divider_32_20_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# XDC: c:/Users/Julia/Desktop/hdmi_vga_zybo2/hdmi_vga_zybo.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_vp_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Julia/Desktop/hdmi_vga_zybo2/hdmi_vga_zybo.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0.xci
# IP: The module: 'hdmi_vga_vp_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Julia/Desktop/hdmi_vga_zybo2/hdmi_vga_zybo.srcs/sources_1/ip/median5x5_0_3/median5x5_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==median5x5_0 || ORIG_REF_NAME==median5x5_0} -quiet] -quiet

# IP: C:/Users/Julia/Desktop/hdmi_vga_zybo2/hdmi_vga_zybo.srcs/sources_1/ip/thresh_0_2/thresh_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==thresh_0 || ORIG_REF_NAME==thresh_0} -quiet] -quiet

# IP: C:/Users/Julia/Desktop/hdmi_vga_zybo2/hdmi_vga_zybo.srcs/sources_1/ip/rgb2ycbcr_0/rgb2ycbcr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb2ycbcr_0 || ORIG_REF_NAME==rgb2ycbcr_0} -quiet] -quiet

# IP: c:/Users/Julia/Desktop/hdmi_vga_zybo2/hdmi_vga_zybo.srcs/sources_1/ip/delayLineBRAM/delayLineBRAM.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM} -quiet] -quiet

# IP: C:/Users/Julia/Desktop/hdmi_vga_zybo2/hdmi_vga_zybo.srcs/sources_1/ip/divider_32_20_0_1/divider_32_20_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# XDC: c:/Users/Julia/Desktop/hdmi_vga_zybo2/hdmi_vga_zybo.gen/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_vga_vp_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
