# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Julia/Desktop/hdmi_vga_zybo1/hdmi_vga_zybo.srcs/sources_1/ip/suma_ak/suma_ak.xci
# IP: The module: 'suma_ak' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Julia/Desktop/hdmi_vga_zybo1/hdmi_vga_zybo.gen/sources_1/ip/suma_ak/suma_ak_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'suma_ak'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Julia/Desktop/hdmi_vga_zybo1/hdmi_vga_zybo.srcs/sources_1/ip/suma_ak/suma_ak.xci
# IP: The module: 'suma_ak' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Julia/Desktop/hdmi_vga_zybo1/hdmi_vga_zybo.gen/sources_1/ip/suma_ak/suma_ak_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'suma_ak'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
